In [3]:
import requests
from pymeteosource.api import Meteosource
from pymeteosource.types import tiers, sections, langs, units
import pandas as pd
import datetime
today = datetime.date.today()
today = today.strftime("%Y-%m-%d")

# pip install pymeteosource
# pip install pymeteosource[pandas]

API_KEY = '3zwarn7ip5qrtgt3j8f1ne9natizvnsaqm05llya'
TIER = tiers.FREE

meteosource = Meteosource(API_KEY, TIER)
cities = ['madrid', 'barcelona', 'valencia']
daily_df = pd.DataFrame()

for city in cities:
    forecast = meteosource.get_point_forecast(
        place_id=city,
        sections=[sections.DAILY],
        lang=langs.ENGLISH,
        units=units.METRIC,
        tz='Europe/Madrid'
    )

    # Convertir los datos diarios a un DataFrame de pandas
    data = forecast.daily.to_pandas()

    # AÃ±adir una columna con el nombre de la ciudad
    data['city'] = city

    # AÃ±adir una columna con la fecha correspondiente
    data['date'] = data.index
    data['date_prediction'] = today

    # Concatenar al DataFrame principal
    daily_df = pd.concat([daily_df, data], ignore_index=True)

# Mostrar las primeras filas del DataFrame
daily_df.head(10)

,afternoon,all_day_cloud_cover_total,all_day_icon,all_day_precipitation_total,all_day_precipitation_type,all_day_temperature,all_day_temperature_max,all_day_temperature_min,all_day_weather,all_day_wind_angle,all_day_wind_dir,all_day_wind_speed,evening,icon,morning,summary,weather,city,date,date_prediction
0,None,61,5,0.0,none,18.2,22.8,14.0,mostly_cloudy,34,NNE,3.0,None,5,None,Partly sunny changing to cloudy by afternoon a...,mostly_cloudy,madrid,2025-05-22,2025-05-22
1,None,32,4,0.0,none,16.0,22.2,8.8,partly_sunny,63,ENE,3.9,None,4,None,"Partly sunny, fewer clouds in the afternoon. T...",partly_sunny,madrid,2025-05-23,2025-05-22
2,None,14,3,0.0,none,17.5,25.2,9.5,mostly_sunny,99,E,1.9,None,3,None,"Sunny, more clouds in the afternoon. Temperatu...",mostly_sunny,madrid,2025-05-24,2025-05-22
3,None,15,4,0.0,none,20.0,27.8,11.5,partly_sunny,80,E,1.7,None,4,None,"Sunny, more clouds in the afternoon and evenin...",partly_sunny,madrid,2025-05-25,2025-05-22
4,None,53,4,0.0,none,21.8,28.5,15.2,partly_sunny,33,NNE,1.8,None,4,None,"Partly sunny, more clouds in the evening. Temp...",partly_sunny,madrid,2025-05-26,2025-05-22
5,None,27,4,0.0,none,22.0,28.2,15.8,partly_sunny,39,NE,2.4,None,4,None,"Sunny, more clouds in the evening. Temperature...",partly_sunny,madrid,2025-05-27,2025-05-22
6,None,31,4,0.0,none,23.0,30.5,15.5,partly_sunny,53,NE,1.6,None,4,None,"Partly sunny, fewer clouds in the afternoon. T...",partly_sunny,madrid,2025-05-28,2025-05-22
7,None,53,4,1.1,rain,17.2,18.2,15.0,partly_sunny,160,SSE,2.4,None,4,None,Rain showers changing to mostly cloudy in the ...,partly_sunny,barcelona,2025-05-22,2025-05-22
8,None,25,4,0.0,none,19.0,23.0,13.8,partly_sunny,204,SSW,2.7,None,4,None,"Sunny, more clouds in the afternoon and evenin...",partly_sunny,barcelona,2025-05-23,2025-05-22
9,None,39,4,0.0,none,18.8,21.8,14.5,partly_sunny,162,SSE,2.8,None,4,None,Partly sunny. Temperature 15/22 Â°C.,partly_sunny,barcelona,2025-05-24,2025-05-22

In [4]:
daily_df.to_csv(r'C:\Users\ej.garcia\OneDrive - Minor Hotels Europe & Americas\Documentos\GitHub\Useful_Scripts\0.Data_Weather\daily_weather.csv', sep=";",mode='a',index=False,header=False)